apiVersion: queries.api-callers.io/v1
kind: Keyspace
metadata:
    name: lostark
    namespace: api-callers
spec:
    default-limit-rate:
      '60': '100'
---
apiVersion: queries.api-callers.io/v1
kind: APIQuery
metadata:
    name: max-item-level
    namespace: api-callers
    labels:
      queries.api-callers.io/keyspace: lostark
spec:
    url: https://developer-lostark.game.onstove.com/characters/{characterName}/siblings
    method: GET
    result:
      serverName: $[?(@.CharacterName=="{characterName}")].ServerName
      maxLevel: max($[?(@.ServerName=="{serverName}")].ItemMaxLevel)

---
apiVersion: queries.api-callers.io/v1
kind: APIQuery
metadata:
    name: expedition-level
    namespace: api-callers
    labels:
      queries.api-callers.io/keyspace: lostark
spec:
    url: https://developer-lostark.game.onstove.com/armories/characters/{characterName}/profiles
    method: GET
    result:
      expeditionLevel: $.ExpeditionLevel

---
apiVersion: queries.api-callers.io/v1
kind: APIQuery
metadata:
    name: search-gem-price
    namespace: api-callers
    labels:
      queries.api-callers.io/keyspace: lostark
spec:
    url: https://developer-lostark.game.onstove.com/auctions/items
    method: POST
    variables:
      level:
        type: int
        required: true
      gemtype:
        type: string
        required: true
    data: |
      {
        "Sort": "BUY_PRICE",
        "CategoryCode": 210000,
        "ItemName": "{level}레벨 {gemtype}의 보석",
        "PageNo": 0,
        "SortCondition": "ASC"
      }
    result:
      minPrice: $.Items.$0.AuctionInfo.BuyPrice

---
apiVersion: queries.api-callers.io/v1
kind: APIQuery
metadata:
    name: search-stone-price
    namespace: api-callers
    labels:
      queries.api-callers.io/keyspace: lostark
spec:
    url: https://developer-lostark.game.onstove.com/auctions/items
    method: POST
    variables:
      stoneValue1:
        type: int
        required: true
      stoneValue2:
        type: int
        required: true
    data: |
      {
        "EtcOptions": 
        [
          {
            "FirstOption": 3,
            "SecondOption": "{stoneValue1}"
          },
          {
            "FirstOption": 3,
            "SecondOption": "{stoneValue2}"
          }
        ],
        "Sort": "BUY_PRICE",
        "CategoryCode": 30000,
        "ItemTier": null,
        "ItemGrade": "유물",
        "PageNo": 0,
        "SortCondition": "ASC"
      }
    result:
      prices: $.Items[:].AuctionInfo.BuyPrice
      options: $.Items[:].Options.OptionName