apiVersion: keys.qouriers.io/v1
kind: Keyspace
metadata:
    name: riot
    namespace: qouriers
spec:
    default-limit-rate:
      '1': '20'
      '120': '100'
    inject-key:
      http-headers:
        X-Riot-Token: '{token}'
---
apiVersion: queries.qouriers.io/v1
kind: APIQuery
metadata:
    name: summoner-by-name
    namespace: qouriers
    labels:
      keys.qouriers.io/keyspace: riot
spec:
    url: https://kr.api.riotgames.com/lol/summoner/v4/summoners/by-name/{summonerName}
    method: GET
    result:
      json:
        puuid: first($.puuid)
---
apiVersion: queries.qouriers.io/v1
kind: APIQuery
metadata:
    name: matchids-by-puuid
    namespace: qouriers
    labels:
      keys.qouriers.io/keyspace: riot
spec:
    url: https://asia.api.riotgames.com/lol/match/v5/matches/by-puuid/{puuid}/ids
    method: GET
    variables:
      startTime: 
        type: int
      endTime:
        type: int
      queue:
        type: int
      type:
        type: string
      start:
        type: int
        default: '0'
      count:
        type: int
        default: '20'
    result:
      json:
        matchids: $[:]
---
apiVersion: queries.qouriers.io/v1
kind: APIQuery
metadata:
    name: match-participants-by-matchid
    namespace: qouriers
    labels:
      keys.qouriers.io/keyspace: riot
spec:
    url: https://asia.api.riotgames.com/lol/match/v5/matches/{matchid}
    method: GET
    result:
      json:
        participants: $.metadata.participants[:]
        championIds: $.info.participants[:].championId
        championNames: $.info.participants[:].championName
        championLevels: $.info.participants[:].champLevel
        kills: $.info.participants[:].kills
        deaths: $.info.participants[:].deaths
        assists: $.info.participants[:].assists
        earnedGolds: $.info.participants[:].goldEarned
        damages: $.info.participants[:].totalDamageDealtToChampions
      
      
