apiVersion: v1
kind: ServiceAccount
metadata:
  name: qourier-quick
  namespace: qouriers
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qourier-quick
  namespace: qouriers
subjects:
- kind: ServiceAccount
  name: qourier-quick
roleRef:
  kind: Role
  name: qourier-sender
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qourier-quick
  name: qourier-quick
  namespace: qouriers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qourier-quick
  template:
    metadata:
      labels:
        app: qourier-quick
    spec:
      serviceAccountName: qourier-quick
      containers:
      - image: qouriers:latest
        name: qourier-quick
        args: 
        - "app.quick:app"
        ports:
        - containerPort: 80
        imagePullPolicy: Never
        readinessProbe:
          httpGet:
            path: /apiqueries
            port: 80
          periodSeconds: 60
          timeoutSeconds: 5
        volumeMounts:
          - name: podinfo
            mountPath: /etc/podinfo
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
