apiVersion: v1
kind: Service
metadata:
  labels:
    app: qourier-queue
  name: qourier-queue
  namespace: qouriers
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: qourier-queue
  type: NodePort
