apiVersion: v1
kind: ServiceAccount
metadata:
  name: qourier-caller
  namespace: qouriers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qourier-caller
  namespace: qouriers
rules:
- apiGroups:
  - keys.qouriers.io
  resources:
  - keyspaces
  verbs:
  - get
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qourier-queue
  namespace: qouriers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qourier-queue
  namespace: qouriers
rules:
- apiGroups:
  - queries.qouriers.io
  resources:
  - apiqueries
  verbs:
  - get
  - list 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qourier-quick
  namespace: qouriers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qourier-quick
  namespace: qouriers
rules:
- apiGroups:
  - queries.qouriers.io
  resources:
  - apiqueries
  verbs:
  - get
  - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qourier-caller
  namespace: qouriers
subjects:
- kind: ServiceAccount
  name: qourier-caller
roleRef:
  kind: Role
  name: qourier-caller
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qourier-queue
  namespace: qouriers
subjects:
- kind: ServiceAccount
  name: qourier-queue
roleRef:
  kind: Role
  name: qourier-queue
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qourier-quick
  namespace: qouriers
subjects:
- kind: ServiceAccount
  name: qourier-quick
roleRef:
  kind: Role
  name: qourier-quick
  apiGroup: rbac.authorization.k8s.io