apiVersion: v1
kind: ServiceAccount
metadata:
  name: qourier-caller
  namespace: qouriers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qourier-caller
  namespace: qouriers
rules:
- apiGroups:
  - keys.qouriers.io
  resources:
  - keyspaces
  verbs:
  - get
  - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qourier-caller
  namespace: qouriers
subjects:
- kind: ServiceAccount
  name: qourier-caller
roleRef:
  kind: Role
  name: qourier-caller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qourier-queue
  namespace: qouriers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qourier-queue
  namespace: qouriers
rules:
- apiGroups:
  - queries.qouriers.io
  resources:
  - apiqueries
  verbs:
  - get
  - list 
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qourier-queue
  namespace: qouriers
subjects:
- kind: ServiceAccount
  name: qourier-queue
roleRef:
  kind: Role
  name: qourier-queue
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qourier-quick
  namespace: qouriers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qourier-quick
  namespace: qouriers
rules:
- apiGroups:
  - queries.qouriers.io
  resources:
  - apiqueries
  verbs:
  - get
  - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qourier-quick
  namespace: qouriers
subjects:
- kind: ServiceAccount
  name: qourier-quick
roleRef:
  kind: Role
  name: qourier-quick
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qourier-key-manager
  namespace: qouriers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: qourier-key-manager
  namespace: qouriers
rules:
- apiGroups:
  - keys.qouriers.io
  resources:
  - keyspaces
  verbs:
  - list
  - get
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - list
  - patch
  - create
  - delete
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - list
  - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qourier-key-manager
subjects:
- kind: ServiceAccount
  namespace: qouriers
  name: qourier-key-manager
roleRef:
  kind: ClusterRole
  name: qourier-key-manager
  apiGroup: rbac.authorization.k8s.io
