apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qourier-caller
  namespace: qouriers
rules:
- apiGroups:
  - keys.qouriers.io
  resources:
  - keyspaces
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qourier-sender
  namespace: qouriers
rules:
- apiGroups:
  - queries.qouriers.io
  resources:
  - apiqueries
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: qourier-key-manager
  namespace: qouriers
rules:
- apiGroups:
  - keys.qouriers.io
  resources:
  - keyspaces
  verbs:
  - list
  - get
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - list
  - patch
  - create
  - delete
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - list
  - patch