apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apiqueries.queries.api-callers.io
spec:
  group: queries.api-callers.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                url:
                  type: string
                method:
                  type: string
                data:
                  type: string
                  default: '{}'
                variables:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                result:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              required:
                - url
                - method
                  
  scope: Namespaced
  names:
    plural: apiqueries
    singular: apiquery
    kind: APIQuery
    shortNames:
    - apiq