apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apiqueries.queries.qouriers.io
spec:
  group: queries.qouriers.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                url:
                  type: string
                method:
                  type: string
                data:
                  type: string
                  default: '{}'
                input:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                variables-required:
                  type: array
                  items:
                    type: string
                output:
                  type: object
                  properties:
                    json:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    html:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
              required:
                - url
                - method
                  
  scope: Namespaced
  names:
    plural: apiqueries
    singular: apiquery
    kind: APIQuery
    shortNames:
    - apiq