apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keyspaces.keys.qouriers.io
spec:
  group: keys.qouriers.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                default-limit-rate:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                inject-key:
                  type: object
                  properties:
                    http-headers:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    query-params:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                  
  scope: Namespaced
  names:
    plural: keyspaces
    singular: keyspace
    kind: Keyspace
    shortNames:
    - ks