apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: keyspaces.queries.api-callers.io
spec:
  group: queries.api-callers.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                inject-key:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                default-limit-rate:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  
  scope: Namespaced
  names:
    plural: keyspaces
    singular: keyspace
    kind: Keyspace
    shortNames:
    - ks